apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres.name }}-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.postgres.storage }}
  storageClassName: standard
