express:
    replicasCount: 1
    image:
        repository: ring0exec/http-backend
        tag: 6e2113b11bf050d4ced8aff87fffc720d7cb106a
        pullPolicy: Always
        pullSecret: regcred
    ports:
        name: http
        port: 3001
        containerPort: 3001
    resources:
        requests:
            cpu: "50m"
            memory: "128Mi"
        limits:
            cpu: "500m"
            memory: "1Gi"
    autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 90
        targetMemoryUtilizationPercentage: 90