express:
    replicasCount: 1
    image:
        repository: ring0exec/http-backend
        tag: fcc31e9869a596a29b245efbc3b4089999a18f60
        pullPolicy: Always
        pullSecret: regcred
    ports:
        name: http
        port: 3001
        containerPort: 3001
    resources:
        requests:
            cpu: "100m"
            memory: "256Mi"
        limits:
            cpu: "250m"
            memory: "1Gi"
    autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 90
        targetMemoryUtilizationPercentage: 90