express:
    replicasCount: 1
    image:
        repository: ring0exec/http-backend
        tag: 25e872080d327f03d92458ee2d5a6a36a92be7d0
        pullPolicy: Always
        pullSecret: regcred
    ports:
        name: http
        port: 3001
        containerPort: 3001
    resources:
        requests:
            cpu: "100m"
            memory: "256Mi"
        limits:
            cpu: "500m"
            memory: "1Gi"
    autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 90
        targetMemoryUtilizationPercentage: 90