express:
    replicasCount: 1
    image:
        repository: ring0exec/http-backend
        tag: cfde6765abeb5ea7d049f80ef1c53ed1d90aebba
        pullPolicy: Always
        pullSecret: regcred
    ports:
        name: http
        port: 3001
        containerPort: 3001
    resources:
        requests:
            cpu: "100m"
            memory: "256Mi"
        limits:
            cpu: "500m"
            memory: "1Gi"
    autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 90
        targetMemoryUtilizationPercentage: 90