express:
    replicasCount: 1
    image:
        repository: ring0exec/http-backend
        tag: c20b11465e625d43f502dc01df61f9e8cc7a1d72
        pullPolicy: Always
        pullSecret: regcred
    ports:
        name: http
        port: 3001
        containerPort: 3001
    resources:
        requests:
            cpu: "50m"
            memory: "128Mi"
        limits:
            cpu: "500m"
            memory: "1Gi"
    autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 90
        targetMemoryUtilizationPercentage: 90