apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Torque-Lab/mointering.git
    targetRevision: main
    path: mointering/charts/rabbitmq
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
