apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true 
spec:
  project: default
  source:
    repoURL: https://github.com/Torque-Lab/mointering.git
    targetRevision: main
    path: mointering/charts/worker-backend
    helm:
      valuesFiles:
        - apps/backend/updated_images/worker-values.yaml  
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
