apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "-21"
spec:
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      name: {{ .Values.nextjs.ports.name }}
      port: {{ .Values.nextjs.ports.port }}
      targetPort: {{ .Values.nextjs.ports.containerPort }}
  type: ClusterIP
