apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      name: {{ .Values.nextjs.ports.name }}
      port: {{ .Values.nextjs.ports.port }}
      targetPort: {{ .Values.nextjs.ports.containerPort }}
type: ClusterIP