worker:
    replicasCount: 1
    image:
        repository: ring0exec/worker-backend
        tag: cea23282d687e9291650db0eb28884fc0eb28510
        pullPolicy: Always
        pullSecret: regcred
    ports:
        name: http
        port: 3002
        containerPort: 3002
    resources:
        requests:
            cpu: "200m"
            memory: "256Mi"
        limits:
            cpu: "500m"
            memory: "1Gi"
    autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 90
        targetMemoryUtilizationPercentage: 90