apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  namespace: frontend
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sitewatch.suvidhaportal.com
      secretName: sitewatch-tls
  rules:
    - host: sitewatch.suvidhaportal.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-service
                port:
                  number: 3000 
          # - path: /api
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: express-service
          #       port:
          #         number: 3001
