apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.rabbitmq.syncWave }}
spec:
  replicas: {{ .Values.rabbitmq.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}
          ports:
            - containerPort: {{ .Values.rabbitmq.ports.containerPort }}
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}