apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  annotations:
    argocd.argoproj.io/sync-wave: "-27"
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      name: amqp
      port: 5672
      targetPort: 5672
  type: ClusterIP