---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: global-secret
spec:
  encryptedData:
    PASSWORD: AgBg7KGOcm/zWLpjnLXzrDYVwYGHqlZf4IYdDk/PArZjHrqtaG0QY+XzqBq5daMARdFNJckDQFT4K1t2uWHoHdoYuHkcOPo/5ofc0lMZnT14iXAaVf181PSNLjSI/71I4qw4ywd1lAjP1lcRiFc+efsjSr+U0j9HweSCbqFDJgjE12SFCdUDi8Pp9Ar725WTo9CZfJzTNwV172Ca4Loj+5MzjhlOUNRID/xtqdiDcnDzN9KqruoMkS4hY3dsudpWo3N9S5Dz+553VtC/5Gr1DCfnqrcKWJY323tENU9MxpbbTMArCjxGo3g7UxcOSeL+NrV6y3fPd9NaoW6HP4UaNn0Y6iEURUDkNX8RaG1rQTskrmX6AY0eCqPFPQjcBCQOqHIDcxFXVNB/BWONOOLwOXg9jRCQuuqvpI5q+7CX/W/UU2qL1TG91n6x2pgr9r4HF2/5lxC9QEbO48SnjiF3pI/H7CtBea/cBaxM/Zo4CujBBjlr6/70p0eTU4RW95r/cX+LeZR6MyfJbmUCwVGW+h5VE9JsJay6gR62P1x6lmNggSDbuYcsn3NKAR9Wq8sya+3gefL8zwhh/Ehx4wR5ZHkf5Ea56RlLi1s2VfhtpHY7SvVUcyLEKJo+pP9HDic2vvrvppsMYppYPDqE7oW5jPVaV0nVlJ1A/o8mkSMeI6UZ3ivn9Q7+AHx/b/5l8WnNenw/I4pjrKe7HRsVJA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: global-secret
