rabbitmq:
    replicasCount: 1
    image:
        repository: rabbitmq
        tag: latest
        pullPolicy: Always
        
    ports:
        name: amqp
        port: 5672
        containerPort: 5672
    syncWave: "-24"

    resources:
        requests:
            cpu: "200m"
            memory: "512Mi"
        limits:
            cpu: "1000m"
            memory: "2Gi"
