apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  replicas: {{ .Values.express.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.express.image.repository }}:{{ .Values.express.image.tag | default .Chart.AppVersion | quote }}
          imagePullPolicy: {{ .Values.express.image.pullPolicy }}
          imagePullSecrets:
            - name: {{ .Values.express.image.pullSecret }}
          ports:
            - name: {{ .Values.express.ports.name }}
              port: {{ .Values.express.ports.port }} 
              containerPort: {{ .Values.express.ports.containerPort }}
          resources:
            {{- toYaml .Values.express.resources | nindent 12 }}
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: REDIS_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: DATABASE_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: RABBITMQ_URL
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: RESEND_API_KEY
            - name: JWT_SECRET_ACCESS
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: JWT_SECRET_ACCESS
            - name: JWT_SECRET_REFRESH
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: JWT_SECRET_REFRESH
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: NODE_ENV
            - name: NEXT_PUBLIC_URL
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: NEXT_PUBLIC_URL
           
