apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: express
  ports:
    - protocol: TCP
      name: {{ .Values.express.ports.name }}
      port: {{ .Values.express.ports.port }}
      targetPort: {{ .Values.express.ports.containerPort }}
  type: ClusterIP
