nextjs:
    replicasCount: 1
    image:
        repository: ring0exec/frontend
        tag: 62ca8df073a693538f8bbb79c52aa216e0dbc9cf
        pullPolicy: Always
        pullSecret: regcred
    ports:
        name: http
        port: 3000
        containerPort: 3000
    resources:
        requests:
            cpu: "100m"
            memory: "256Mi"
        limits:
            cpu: "500m"
            memory: "1Gi"
    autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80