nextjs:
    replicasCount: 1
    image:
        repository: ring0exec/frontend
        tag: 755b42b505c15b55229ddf55d7eec3a3acee7435
        pullPolicy: Always
        pullSecret: regcred
    ports:
        name: http
        port: 3000
        containerPort: 3000
    resources:
        requests:
            cpu: "50m"
            memory: "128Mi"
        limits:
            cpu: "500m"
            memory: "1Gi"
    autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80