apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  annotations:
    argocd.argoproj.io/sync-wave: "-29"
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.redis.ports.port }}
      targetPort: {{ .Values.redis.ports.containerPort }}
  type: ClusterIP